
version: "3.9"
services:

    server_bank:
        build: ./backend
        container_name: back_end
        ports:
            - '5000:80'
        depends_on:
            - mysql_bank

    mysql_bank:
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: react_bank
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        image: mysql:5.7
        ports:
            - '3306:3306'

    client-bank:
        build: ./frontend
        container_name: front-end
        ports:
            - '3000:3000'
        depends_on:
            - server-bank
        stdin_open: true
