
version: "3.9"
services:

    mysql_bank:
        container_name: mysql_bank
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: react_bank
        image: mariadb
        ports:
            - '3306:3306'

    server_bank:
        build: ./backend
        container_name: server_bank
        ports:
            - '5000:80'
        depends_on:
            - mysql_bank
        dns: 8.8.8.8
        command: sh ./commands.sh
        
    client_bank:
        build: ./frontend
        container_name: client_bank
        ports:
            - '3000:3000'
        depends_on:
            - server_bank
        stdin_open: true
